language: node_js
sudo: true
dist: trusty
node_js:
  - 10
branches:
  except:
  - /^v[0-9]/
install:
  - yarn install
  - yarn global add codecov
  - yarn global add ts-node
script:
  - yarn bootstrap
  - yarn run test
  - yarn bundle

after_success:
  - codecov
deploy:
  skip_cleanup: true
  provider: script
  script: yarn run publish
  on:
    branch: master
cache:
  directories:
  - "$HOME/.yarn-cache"
