language: node_js
sudo: true
jobs:
  include:
    - os: linux
      dist: xenial
      node_js:
        - 12
    - os: linux
      dist: xenial
      node_js:
        - 14
    - os: linux
      dist: xenial
      node_js:
        - 16
    - os: linux
      dist: bionic
      node_js:
        - 12
    - os: linux
      dist: bionic
      node_js:
        - 14
    - os: linux
      dist: bionic
      node_js:
        - 16
    - os: osx
      node_js:
        - 12
    - os: osx
      node_js:
        - 14
    - os: osx
      node_js:
        - 16
branches:
  except:
  - /^v[0-9]/
install:
  - yarn install
  - yarn global add codecov
  - yarn global add ts-node
  - yarn global add webpack
script:
  - yarn bootstrap
  - yarn run test
  - yarn validate
  - yarn bundle
  - yarn build:web
after_success:
  - codecov
cache:
  directories:
  - "$HOME/.yarn-cache"
